### ISSUE TITLE
SATOLD calculation for first time-step

### ISSUE THREAD

**Issue by vivekbedekar** [MODFLOW-USGS/mt3d-usgs#36]
Eric,

We need to verify if the SATOLD calculation for the first time-step is correct.

Vivek

**Comment by emorway-usgs** [comment]
@vivekbedekar do you remember which commit included the change related to this issue?

**Comment by emorway-usgs** [comment]
See commit 7e75f9b

Here are a few things you need to verify in the code:

1. Please make sure that SATOLD calculation is correct for the first time step. I have coded it but could not QA it. Please QA that with a dummy example with a first transient stress period.
2. Handing of UZT input for water content. I have commented the calculation of THETAW in the UZT reading routine.
3. I have added a check in the code to compare WC and porosity. For the Trout Lake problem, the run stops because of the if check since WC exceeds porosity (0.4927 versus 0.29). Could you verify if the new if check makes sense or if the WC passed in the FTL file has an issue.
 
Please run both the Keating and the Trout Lake problem and check whether these new changes helped.

**Comment by emorway-usgs** [comment]
Passed on Travis
