### ISSUE TITLE
Error reading formatted fll file

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#54]
If the ftl file is formatted, MT3D doesn't accurately identify when the UZF package is active. I have a suggested fix.

Here are lines 127-132 of fmi1.f with the fix included. The problem is that when the ftl file is formatted, the read statement has the text followed by blanks but in the tests that follow, it is assumed that the text is preceded by blanks. The fix is to us ADJUSTR on the text. 
            IF(IFTLFMT.EQ.0) THEN
              READ(INFTL) TEXT1
            ELSEIF(IFTLFMT.EQ.1) THEN
              READ(INFTL,*) TEXT1
              TEXT1 = ADJUSTR(TEXT1)
            ENDIF

While this corrects this particular problem, the model still won't run because of another bug.
[mt3d_bug.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/3113772/mt3d_bug.zip)

**Comment by emorway-usgs** [comment]
@rbwinst-usgs I thinking this is related to #55 because of the way the linker file opened up when specified in both the name file and the LMT input file.  I'm leaning toward closing the linker file if it was opened in the MF name file and reopening it using LMT protocol.   I think this will clear up most of these issues, but want to get confirmation from @langevin-usgs that I'm not overlooking something else.  

I think the quickest path forward if this is holding you up is to remove specification of the linker file (.ftl in this case) from the MF name file.  I don't think the intention was to open a linker file in the MF name file, but only in LMT?
