### ISSUE TITLE
Error reading UZF RECHARGE from formatted ftl file

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#55]
When READPS attempts to read the data for "UZF RECHARGE" from a formatted ftl file, it doesn't read it properly. It only read "UZF" instead of "UZF RECHARGE"
[mt3d_bug.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/3113853/mt3d_bug.zip)
![bug2](https://user-images.githubusercontent.com/10761318/56687357-14bb4e00-66a4-11e9-979d-b998e8299880.png)

**Comment by emorway-usgs** [comment]
In the screen capture below, note the presence/absence of single quotations around the text.  Their presence (or lack there of) seems to hinge upon whether the linker file name and unit number appears in the name file.  It is not necessary to list (instantiate) the linker file in the name file - using the .lmt file to specify the name (and unit #) of the linker file will get the job done, and seems to write the linker file with the single quotes which allows the small example problem included with this issue to run correctly (at least on my machine).  The quickest work-around for this problem is to simply remove the the linker file, in this case the .ftl file, from the modflow name file.  

I'll continue looking into a more permanent fix, however.

![quotes](https://user-images.githubusercontent.com/3236576/57785829-4cd41080-76e7-11e9-942a-06f9fd7f6b32.PNG)

**Comment by emorway-usgs** [comment]
@langevin-usgs The culprit in this bug report is the DELIM='APOSTROPHE' in the LMT package, see on or near line 463 in lmt.f (3rd to last line in the code below):

```
      INQUIRE(UNIT=IUMT3D,OPENED=LOP)
      IF(LOP) THEN
        REWIND (IUMT3D)
      ELSE
        IF(ILMTFMT.EQ.0) THEN
          OPEN(IUMT3D,FILE=FNAME,FORM=FORM,ACCESS=ACCESS,
     &      ACTION=ACTION(2),STATUS='REPLACE')
        ELSEIF(ILMTFMT.EQ.1) THEN
          OPEN(IUMT3D,FILE=FNAME,FORM='FORMATTED',ACTION=ACTION(2),
     &      STATUS='REPLACE',DELIM='APOSTROPHE')
        ENDIF
      ENDIF
```
The best work around that is backward compatible for keeping the FTL file specification in the name file is to close the unit number opened in the name file if it is the same as what's in LMT and reopen it using the LMT method, I think?  So essentially what will happen is that if the linker file is specified in the name file, it will essentially be ignored.  Otherwise, it is unclear how to detect the special case of opening the linker file from within the MODFLOW name file because the type is `DATA` or `DATA(BINARY)` which is a general case.  We should discuss before I push forward.

**Comment by emorway-usgs** [comment]
The fix for this issue is documented in the MF-NWT repo, see [this issue](https://github.com/rniswon/mfnwt/issues/35).  @rbwinst-usgs if you remove all listings of the actual linker file from the MODFLOW name file, I think these FTL issues that you are having will go away.  At your convenience, could you confirm that to be the case, and if so, close the FTL issues [#54, this one (#55), #56, & #57]?
