### ISSUE TITLE
SSM not read correctly with MODFLOW 6

### ISSUE THREAD

**Issue by RichardWinston** [MODFLOW-USGS/mt3d-usgs#67]
When reading the SSM file, MT3D-USGS skips reading INCRCH and instead reads NSS where it should be reading INCRCH causing it to fail.
[Mt3d_MF6_Tests.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/3387896/Mt3d_MF6_Tests.zip)

**Comment by emorway-usgs** [comment]
@RichardWinston Turns out this is more of a documentation problem than a source code issue.  I'm realizing that I failed to make note in the input_instructions.pdf document distributed with MT3D-USGS (v1.1.0) that when running MT3D-USGS with MF6-generated linker files, RCH and EVT data needs to be written into SSM using the NSS list, not the typical CRCH and CEVT arrays.  

When adding support for MF6, this was an easier path to go since MF6 is write the IRCH array to any of the linker files.  Recall that IRCH is a 2D array written into the classic FTL linker file (by the LMT package) instructing MT3D which layer the recharge is occuring in.  Thus, by requiring the user to use the list-based approach, they can specify which layer the RCH concentration needs to go with.  I'm attaching a working SSM file to this follow-up.  I made the extention .txt as git wouldn't allow me to attach a file with the .ssm file extension.

Please also note that your SSM file did not have any entries for the constant head cells in your flow model, so I went ahead and added them and took a guess that the associated concentration was 0.0.  Please change as necessary.  

Lastly, I had to change MIXELM to 0 (from a value of 3).  This may be a bug, but I need to discuss further with @langevin-usgs .  We didn't test the MF6 support with any of the hybrid advection approaches, but only checked using the standard finite different approach.  

[ImportedP10.txt](https://github.com/MODFLOW-USGS/mt3d-usgs/files/3404216/ImportedP10.txt)

**Comment by emorway-usgs** [comment]
@RichardWinston OK, I have cleaned up the documentation and pushed such that updated input_instructions.pdf will go out with the next release.  However, this issue did identify a bug that is discussed in issue #68 

The model attached to the initial post (in this thread) should now be working if you use the .ssm input file attached to the second posting in [this thread](https://github.com/MODFLOW-USGS/mt3d-usgs/issues/67).
